### ISSUE TITLE
撤回的时候，能不能通知一下对方撤回

### ISSUE THREAD

**Issue by vanroving** [Gh0u1L5/WechatMagician-Abundant#3]

**Comment by Gh0u1L5** [comment]
这个我没太看懂？是说防撤回的时候提示对方撤回失败吗？目前的话对方撤回消息是能看到原本的“撤回了一条消息”的提示的。

**Comment by vipzrx** [comment]
@Gh0u1L5  我理解他 @vanroving 的意思是接收者撤回发送者的消息.这个听起来很疯狂,但是qq之前的版本的有这个漏洞,也有插件实现了.

微信上目前没有看到有撤回发送者消息的插件

以上只是自己的猜测

ps @vanroving 你提了issue 作者也回复了,看到的话,请回复下

**Comment by Gh0u1L5** [comment]
@vipzrx 
哦惊了，还有这种骚操作？这个东西我可以试试看，但是我怀疑这个漏洞已经在服务器那边封上了，因为就是一条if的事。我在数据库里看到过微信消息的数据结构，里面存着消息原本的发送者，如果撤回消息的用户和服务器记录的发送者对不上的话，就可以直接拒绝撤回。

**Comment by vipzrx** [comment]
这个可以撤回别人消息的漏洞,之前在qq上出现过,现在已经和谐了.
微信上没有见过实现这个功能.

我之前理解有误,开这个issue的人意思是说,对方有消息撤回,插件拦截了,在这条消息后面跟上一个提示,说这是一条对方撤回的消息
