### ISSUE TITLE
老铁，使用说明太简短了

### ISSUE THREAD

**Issue by zfk513** [Gh0u1L5/WechatMagician-Abundant#4]
没看懂怎么用 ...是要像app一样放后台？没有设置页面 ，没有恢复页面...

**Comment by Gh0u1L5** [comment]
@zfk513 
这个是需要先安装Xposed框架，然后用Xposed Installer装上去，单独装这个没用的。
装完之后不需要设置，别人发消息给你再想撤回就撤回不了了，只会在原本的消息前面多出“[已撤回]”字样。

**Comment by vipzrx** [comment]
@zfk513 你的是什么手机 什么版本安卓, 看看是否能安装上

**Comment by zfk513** [comment]
嗯 谢谢答复 我装了Xp框架的，在框架上搜索Wechat看到的，安装没问题，只是我原来用微X模块，所以落差挺大的，顺便问下，有大佬知道如何检测朋友圈的三天开放权限吗，不想刷朋友圈但有时候想看又好气看不到

**Comment by Gh0u1L5** [comment]
@zfk513 
微X模块我之前也用过来着，我决定写这个项目的主要原因就是，微X模块实在是太容易崩了……而且基本每次微信更新都一定会挂，要一直等到好几个月才更新……这个项目功能这么有限其实是吸取了微X模块的教训，微X模块绝大多数的崩溃都是由一些基本没人用的功能导致的。很多时候我就想要一个防撤回，结果因为抢红包功能整个微信都闪退了，这种真的好气啊。所以现在这个WechatMagician一开始的定位就是小而精，只做防撤回，只采用最稳定的实现方案。今天我闲着没事从6.5.13升级到6.5.14了，整个插件什么事都没有，安安稳稳地工作着。
朋友圈三天权限那个我今天试了一下，发现用Xposed基本没戏。三天权限的限制是在服务器上检查的，如果朋友设置了三天权限的话，从服务器上拿到的数据也只有三天的内容。而Xposed所有修改都是局限在手机里的，服务器不给数据的话，巧妇难为无米之炊。Xposed 能做到的是什么呢，Xposed 只能是把你以前刷出来过的朋友圈给保住，没刷出来过的就只能GG。

**Comment by crimx** [comment]
同感，微X设计不太成熟，太臃肿了维护起来力不从心，很多功能都是比较潦草的体验。作者对开源也存在误解。
