### ISSUE TITLE
加了一个新功能

### ISSUE THREAD

**Issue by InvisibleMoon** [Gh0u1L5/WechatMagician-Abundant#5]
支持朋友圈内容自动保存成 json, 逆向弄得心力交瘁，没精力做多版本了。有兴趣的话，可以按我 fork 的版本改下，暂时就不提PR了。

**Comment by crimx** [comment]
觉得 Magician 现在的功能挺好的，定位清晰，很简洁。你这个可以做成独立的吧。

**Comment by InvisibleMoon** [comment]
@crimx 微信相关的功能就算符合项目定位吧，而且是 fork 一份在做的。如果作者觉得意义不大，只好考虑自己维护了~

**Comment by crimx** [comment]
@InvisibleMoon 对于增wai强gua类的插件，个人觉得小而精比大而全更重要。一来维护成本增加，二来版本迭代不方便。因为接口稳定性依赖于微信，分开来开发稳定的接口就不需要反复更新。

**Comment by InvisibleMoon** [comment]
@crimx 版本迭代不便这点我也赞同，不过瓶颈在于逆向而非逻辑重构。个人来看，关键还是作者自身定位，当成一个专门的工具蛮好，多些人把规模稍扩大点也未必是坏事。

**Comment by crimx** [comment]
嗯，合并到一起的话最后其实还是作者在管理，得看他精力如何了。

**Comment by vipzrx** [comment]
@InvisibleMoon 

1 我只是小白,听到别人说可以动态hook,比较方便对应不同版本.地址我找到了,发给你
@crimx 
2 多版本的支持的意义在哪里?
能玩xposed的,就是动手能力很强,或者愿意折腾的.微信不断更新,追不上的.能否挑一个好的版本,固定下来,做长期支持.这样对于开发者可以将更多的精力放到研究功能上,对于用户,长期维护一个版本,使用上也稳定

只是我的一点想法,希望进一步交流

**Comment by Gh0u1L5** [comment]
@InvisibleMoon 
新功能什么的我还是挺欢迎的，但是我没太想明白这个功能要加到哪？长按一条朋友圈就能把它保存成json吗？

@crimx @vipzrx 
其实目前为止这个插件一直是多版本兼容的，准确地说，是从6.5.3到目前最新的6.5.13都稳定兼容。这个兼容在最早rarnu写的原始版本里就存在的，当时他的版本是兼容6.5.3到6.5.4。具体方案就是直接硬编码了一个表，对着表查每个微信版本对应什么类什么方法。所以在1.X.X版本里这个兼容一直做得很累，我尽量把所有的操作都局限在数据库层面，这样就不用维护更多类名和方法名了。
直到刚刚发布出来的2.0.0版本里面，我设计了一套机制让插件每次开机自动把我人工逆向的过程用程序做一遍（大概就是你说的动态hook？），接下来应该能安稳很久。

**Comment by crimx** [comment]
@Gh0u1L5 马上用上了！发现个 bug，图片需要点开完全加载的才会变成撤回的图片，如果没有点过缩略图的没有反应。

**Comment by InvisibleMoon** [comment]
@Gh0u1L5 
这边监听了朋友圈的容器类，每次手动刷新时会自动将条目对象序列化并保存，目前的实现会直接输出到日志。
个人的愿景在于，最终将微信作为实时信息源，通过导出的数据做多维度的分析。事实上，除少量代码实现了朋友圈的监听，目前其它工作主要为了使该流程尽可能自动化。不过，即使不考虑这点，微信官方对隐私控制的日益加剧，使得获取信息愈发困难，仅作为一个朋友圈的归档工具，也仍然有其存在价值。

@vipzrx 
个人看来，多版本本质还是成本的权衡。将项目本身视为产品，开发复杂度与用户覆盖是两个维度，在某一方面增加少量损耗，换取另一方面的大幅优势，这样就算是合适的。所以不好一概而论，具体情况具体分析吧。

顺便，我觉得可以建个群，这边想找个能做数据分析的，分身乏术。

**Comment by zfk513** [comment]
支持下作者！！！

**Comment by Gh0u1L5** [comment]
@InvisibleMoon 
我今天随手建了一个QQ群：135955386，目前基本还是空的，欢迎投奔。
你这个想法我觉得很有意思，但是如果可以的话我想给你单开一个branch而不是合并进master里，因为对于大多数用户来说这个功能微妙地鸡肋。绝大部分人都是把朋友圈作为一个即时吐槽的工具，很少有人需要分析或者归档什么的，目前来说没有在release版里增加这个的必要。
另外我读了读你的代码，发现你这个做的还是挺稳的。只要把被混淆过的那几个变量名和方法名处理一下，应该就能兼容绝大部分微信版本。具体处理方法可以参考我在[WechatPackage.kt](https://github.com/Gh0u1L5/WechatMagician/blob/master/src/main/kotlin/com/gh0u1l5/wechatmagician/xposed/WechatPackage.kt)里面写的那套思路。

**Comment by Gh0u1L5** [comment]
@InvisibleMoon @crimx @vipzrx @zfk513 
为了跟已经混吃等死大半年的 rarnu/wechat_no_revoke 断绝关系，我正试着废弃现在这个repo。新repo的地址还是 https://github.com/Gh0u1L5/WechatMagician , 这个旧的被我改名了。如果你们有fork啊watch啊，就挪挪窝呗？
